#ifndef DUELS_GAMESTATE_H
#define DUELS_GAMESTATE_H

namespace duels
{
    
enum State
{
    ONGOING=0,
    WIN_FAIR=1, WIN_TIMEOUT=2, WIN_DISCONNECT=3,
    LOSE_FAIR=4, LOSE_TIMEOUT=5,SERVER_DISCONNECT=6
};

}

#endif // DUELS_GAMESTATE_H
